region: us-east-1

function_name: puppy_writer_lambda
handler: service.handler
role: puppy_writer_lambda
description: Fetches the json stored in s3, and if new, writes each one to MongoDB Atlas. Also sends SMS if baby.
runtime: python3.7

timeout: 500
memory_size: 128
